artifact_location: file:///C:/Users/smart/.gemini/antigravity/scratch/crop-recommendation-system/mlflow/939584014629518354
creation_time: 1771958411535
experiment_id: '939584014629518354'
last_update_time: 1771958411535
lifecycle_stage: active
name: crop_recommendation
workspace: default
